const data = [
    {
        employeeId: "SH001",
        employeeName: "Alice Johnson",
        address: "123 Main St",
        maxHoursPerWeek: 40,
        shiftsAvailable: [
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "NA",
            "NA",
            "Shift 2",
            "Shift 2",
        ],
        payPerHour: 23.0,
    },
    {
        employeeId: "SH002",
        employeeName: "Bob Smith",
        address: "456 Elm Ave",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "NA",
            "Shift 1",
            "Shift 2",
            "Shift 2",
            "NA",
            "Shift 1",
            "Shift 3",
        ],
        payPerHour: 24.0,
    },
    {
        employeeId: "SH003",
        employeeName: "Carol Lee",
        address: "789 Oak Rd",
        maxHoursPerWeek: 30,
        shiftsAvailable: [
            "NA",
            "NA",
            "Shift 3",
            "Shift 1",
            "Shift 1",
            "Shift 2",
            "Shift 3",
        ],
        payPerHour: 25.0,
    },
    {
        employeeId: "SH004",
        employeeName: "David Brown",
        address: "987 Maple Ln",
        maxHoursPerWeek: 38,
        shiftsAvailable: [
            "Shift 1",
            "Shift 1",
            "NA",
            "Shift 3",
            "Shift 3",
            "NA",
            "Shift 2",
        ],
        payPerHour: 26.0,
    },
    {
        employeeId: "SH005",
        employeeName: "Emily Clark",
        address: "567 Pine St",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "Shift 1",
            "Shift 2",
            "Shift 2",
            "Shift 3",
            "Shift 2",
            "Shift 1",
            "Shift 1",
        ],
        payPerHour: 27.0,
    },
    {
        employeeId: "SH006",
        employeeName: "Fiona Green",
        address: "321 Willow St",
        maxHoursPerWeek: 40,
        shiftsAvailable: [
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
        ],
        payPerHour: 28.0,
    },
    {
        employeeId: "SH007",
        employeeName: "George Harris",
        address: "654 Cherry Ave",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
        ],
        payPerHour: 29.0,
    },
    {
        employeeId: "SH008",
        employeeName: "Henry Davis",
        address: "159 Spruce St",
        maxHoursPerWeek: 40,
        shiftsAvailable: [
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
        ],
        payPerHour: 30.0,
    },
    {
        employeeId: "SH009",
        employeeName: "Irene Wilson",
        address: "753 Cedar Ave",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "Shift 2",
        ],
        payPerHour: 31.0,
    },
    {
        employeeId: "SH010",
        employeeName: "Jack Taylor",
        address: "347 Birch Rd",
        maxHoursPerWeek: 30,
        shiftsAvailable: [
            "NA",
            "NA",
            "Shift 3",
            "Shift 1",
            "Shift 1",
            "Shift 2",
            "Shift 3",
        ],
        payPerHour: 32.0,
    },
    {
        employeeId: "SH011",
        employeeName: "Kathy Moore",
        address: "935 Pine Ln",
        maxHoursPerWeek: 38,
        shiftsAvailable: [
            "Shift 1",
            "Shift 1",
            "NA",
            "Shift 3",
            "Shift 3",
            "NA",
            "Shift 2",
        ],
        payPerHour: 33.0,
    },
    {
        employeeId: "SH012",
        employeeName: "Larry White",
        address: "523 Aspen St",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "Shift 1",
            "Shift 2",
            "Shift 2",
            "Shift 3",
            "Shift 2",
            "Shift 1",
            "Shift 1",
        ],
        payPerHour: 34.0,
    },
    {
        employeeId: "SH013",
        employeeName: "Molly Harris",
        address: "211 Oak St",
        maxHoursPerWeek: 40,
        shiftsAvailable: [
            "Shift 2",
            "Shift 3",
            "Shift 1",
            "NA",
            "NA",
            "Shift 2",
            "Shift 2",
        ],
        payPerHour: 35.0,
    },
    {
        employeeId: "SH014",
        employeeName: "Nathan Clark",
        address: "679 Elm Ave",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "NA",
            "Shift 1",
            "Shift 2",
            "Shift 2",
            "NA",
            "Shift 1",
            "Shift 3",
        ],
        payPerHour: 36.0,
    },
    {
        employeeId: "SH015",
        employeeName: "Oscar Lewis",
        address: "147 Maple Rd",
        maxHoursPerWeek: 30,
        shiftsAvailable: [
            "NA",
            "NA",
            "Shift 3",
            "Shift 1",
            "Shift 1",
            "Shift 2",
            "Shift 3",
        ],
        payPerHour: 37.0,
    },
    {
        employeeId: "SH016",
        employeeName: "Patricia Young",
        address: "315 Willow Ln",
        maxHoursPerWeek: 38,
        shiftsAvailable: [
            "Shift 1",
            "Shift 1",
            "NA",
            "Shift 3",
            "Shift 3",
            "NA",
            "Shift 2",
        ],
        payPerHour: 38.0,
    },
    {
        employeeId: "SH017",
        employeeName: "Quincy Thompson",
        address: "793 Cherry St",
        maxHoursPerWeek: 35,
        shiftsAvailable: [
            "Shift 1",
            "Shift 2",
            "Shift 2",
            "Shift 3",
            "Shift 2",
            "Shift 1",
            "Shift 1",
        ],
        payPerHour: 39.0,
    },
];
export default data;